### ISSUE TITLE
Hitbox config option

### ISSUE THREAD

**Issue by zizitt** [FrozenDroid/FrozenGun#2]
Given the nature of how fast pase a normal quake/railgun match is, it's very hard to hit players currently with the extreme precision required by the railgun.

somehow this problem needs to be resolved to make it a smoother experience for all players with different amounts of ping.

**Suggestion:**  _Increase hitbox or something similar to allow greater chance of hitting players._

**Comment by FrozenDroid** [comment]
Done!
